version: '3'

services:
  db:
    image: postgres:9.6.18-alpine
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
  web:
    build: .
    container_name: web
    environment:
      - DJANGO_SETTINGS_MODULE=composeexample.settings_development
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
    pg_data:
      external: true
